PyBracketAccess issue fix
shadaj/scalapy pull request #194
Opened 2021-06-08 22:14 UTC by jlareck

2021-06-09 15:30 UTC, anatoliykmetyuk commented on coreMacros/src/main/scala/me/shadaj/scalapy/py/Facades.scala
> +          paramExprs
Looks like this statement does nothing

2021-06-11 12:24 UTC, jlareck commented
I cleaned up the code and added more options in native_impl method, but I don’t understand in what case we can have None here: https://github.com/shadaj/scalapy/blob/90aeb630738c45ac9419ca6b2f0c30ff1d983371/coreMacros/src/main/scala/me/shadaj/scalapy/py/Facades.scala#L46
Because when I tried to call methods without parameters I got case 0 : https://github.com/shadaj/scalapy/blob/90aeb630738c45ac9419ca6b2f0c30ff1d983371/coreMacros/src/main/scala/me/shadaj/scalapy/py/Facades.scala#L41
Also as we can not use whitebox.context error  because of returned type, I decided to throw ParseException. Maybe it is not the best option but at the moment I don’t know what exception we should throw here in these situations (like if we have 0 parameters or more than 2)

2021-06-28 16:23 UTC, shadaj requested changes
First pass, mostly just nits.

2021-06-28 16:23 UTC, shadaj commented on CHANGELOG.md
> ++ Add support for bracket syntax to facades. The annotation @PyBracketAccess can be used on methods to mark them as representing bracket access on an object. The target method must have one (to read
Need backticks around `@PyBracketAccess` to format correctly. Also, please refer to the PR at the end of the line like in earlier changelog items.

2021-06-28 16:23 UTC, shadaj commented on core/shared/src/test/scala/me/shadaj/scalapy/py/SpecialSyntaxTest.scala
> +// special syntax test for defining pybrackets
Don't need this comment, since we're testing other syntax too.

2021-06-28 16:23 UTC, shadaj commented on core/shared/src/test/scala/me/shadaj/scalapy/py/SpecialSyntaxTest.scala
> +    local{
Nit, need a space between `local` and `{`, and remove the extra space between `val` and `myList`.

2021-06-28 16:23 UTC, shadaj commented on coreMacros/src/main/scala/me/shadaj/scalapy/py/Facades.scala
> +import scala.reflect.macros.ParseException
Unnecessary import?

2021-06-28 16:23 UTC, shadaj commented on coreMacros/src/main/scala/me/shadaj/scalapy/py/Facades.scala
> +    else {
`else` should be on the previous line.

2021-06-28 16:23 UTC, shadaj commented on coreMacros/src/main/scala/me/shadaj/scalapy/py/Facades.scala
> +
Nit: extra indent

2021-06-28 16:23 UTC, shadaj commented on docs/static-types.md
> +The annotation @PyBracketAccess can be used on methods to mark them as representing bracket access on an object. The target method must have one (to read the value) or two parameters (to update the v
Need backticks around `@PyBracketAccess`

2021-06-28 16:23 UTC, shadaj commented on docs/static-types.md
> +The annotation @PyBracketAccess can be used on methods to mark them as representing bracket access on an object. The target method must have one (to read the value) or two parameters (to update the v
Also, can have a better explanation than `representing bracket access on an object`. Perhaps `representing indexing into the Python object using brackets in Python syntax`?

2021-06-28 16:23 UTC, shadaj commented on docs/static-types.md
> +The annotation @PyBracketAccess can be used on methods to mark them as representing bracket access on an object. The target method must have one (to read the value) or two parameters (to update the v
Also, to make the docs more active, we can reword `So, for example, we have` to `For example, we can create`.

2021-06-28 16:23 UTC, shadaj commented on docs/static-types.md
> +Then let's create a python list:
Nit: capitalize Python

2021-06-28 16:23 UTC, shadaj commented on docs/static-types.md
> +val  myList = py"[1, 2, 3]".as[IntList]
Nit: extra space between `val` and `myList`

2021-06-28 16:23 UTC, shadaj commented on docs/static-types.md
> +myList(0) // in python it will call `myList[0]` and return 1
Nit: capitalize Python

2021-06-28 16:23 UTC, shadaj commented on docs/static-types.md
> +And now we can just use brackets to access elements by indexes. For example, we want to get element by index 0:
Nit: `element at index 0` instead of `element by index 0`

2021-06-29 03:17 UTC, shadaj approved these changes
LGTM, great work @jlareck!

2021-06-29 03:19 UTC, merged