Enable setting version of python lib via system property
shadaj/scalapy pull request #198
Opened 2021-06-29 15:44 UTC by kiendang

in order to facilitate automatic setting up ScalaPy since it much easier to set a system property than to set an environment variable in Scala.

2021-06-29 19:00 UTC, shadaj requested changes
Looks great! Could you add an item for this to the changelog?

2021-06-29 19:44 UTC, kiendang commented
Changelog added. I also switched the order so the system property takes precedence over the env var since the former is more controllable. I can switch back if you prefer the way it was.

2021-06-30 16:51 UTC, shadaj requested changes
Having the property take higher precedence sounds good to me. Just one more change needed to link to this PR in the changelog.

2021-06-30 16:51 UTC, shadaj commented on CHANGELOG.md
> ++ The version of the Python native library can now be controlled with the `scalapy.python.library` system property
Could you link to this PR to be consistent with the other items?

2021-06-30 18:35 UTC, shadaj approved these changes

2021-06-30 18:53 UTC, merged